### ISSUE TITLE
Issue in start_commit_process

### ISSUE THREAD

**Issue by satishrdd** [florianmorath/piChain#3]
I was going through your code ,
In the file PaxosLogic.py line no. 677                 propose.new_block = GENESIS.block_id
I do not understand why you are assigning new_block as GENESIS instead of new block,can you please clarify on this.If I am not wrong you are referring to this paper [https://disco.ethz.ch/courses/distsys/lnotes/chapter12_piChain_Ethereum.pdf](url)

**Comment by florianmorath** [comment]
The block b_new in the propose message of Paxos can be seen as the ticket associated with the block being proposed and is checked by a Paxos server on receipt.
At the line you mentioned the node is in a state called “quick proposing” where the protocol differs from the one described in the paper. Quick proposing is an optimization that can be done to skip Phase 1 of Paxos if a node received a majority of propose messages. 
Back to your question:
- To be able to start a new Paxos instance, after every successful commit the Paxos server variables are reset to the initial values which includes the genesis block being assigned to b_max. Since phase 1 is skipped, b_max will remain the genesis block and thus for the ticket in the propose message to be valid, it must also be equal to the genesis block. That is the reason why in the line you wrote the genesis block and not b_new is used.
- I think another way to implement quick proposing (probably as you thought) is to never reset b_max but then you must use b_new from phase 1 as the ticket in the propose message.

I have written a document where I go more into the details of the implementation. There is a section called “quick proposing” which explains the above in more detail. You can access it over the following link: [Implementation of piChain](https://pub.tik.ee.ethz.ch/students/2017-HS/BA-2017-36.pdf)

**Comment by satishrdd** [comment]
Hi,
have a small doubt Is it possible to restrict each transaction to only one block.

**Comment by florianmorath** [comment]
In the paper each block contains one transaction for illustration purposes i.e in theory if a quick node receives a transaction, it immediately creates a block containing it. But by introducing a predefined accumulation time (that depends on the application of piChain) a block may contain multiple transactions. The accumulation time is the time the quick node accumulates transactions before creating a block i.e the quick node does not immediately create a block if it sees a transaction but it waits a little bit for other transactions to arrive. I hope this answers your question.

**Comment by richardhundt** [comment]
There's one thing in the paper which isn't clear to me regarding tickets. You say that the server keeps the highest ticket number seen so far, but the clients are responsible for proposing a ticket number. If the server has the state, how do the clients know what a reasonable next sequence number should be? Do they track these as well? Does every node have a logical clock, and the idea is that these should eventually converge on the same value?

(apologies for resurrecting this closed issue, but I didn't want to open a new issue just for a clarification question)

**Comment by themoodymann** [comment]
Short answer: There are no tickets in piChain. Longer answer: Paxos had tickets which could be chosen arbitrarily... in piChain, blocks are used as tickets.
